name: stress_notificator
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.2.0
  firebase_database: ^11.0.3
  http: ^1.2.1
  firebase_analytics: ^11.2.0
  flutter_local_notifications: ^17.2.1+1
  shared_preferences: ^2.2.3
  firebase_auth: ^5.1.2
  fl_chart: ^0.68.0
  flutter_background: ^1.2.0
  image_picker: ^1.1.2
  firebase_storage: ^12.1.1
  intl: ^0.19.0
  collection: ^1.18.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/gif/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/SN.png"
  min_sdk_android: 26
  remove_alpha_ios: true
